frr version 10.6.1
frr defaults traditional
hostname tpe10-bb-org-t1-r1
log stdout informational
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.41/32
 ipv6 address fd00:6500::41/128
 ip ospf area 0.0.0.0
 ip ospf passive
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 passive
!
interface eth1
 description TPE10-BB-CORE-T1-R1
 ip address 10.0.0.22/31
 ipv6 address fd00:6500:0:c::/127
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 network point-to-point
!
interface eth2
 description TPE10-BB-CORE-T1-R2
 ip address 10.0.0.24/31
 ipv6 address fd00:6500:0:d::/127
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 network point-to-point
!
ip route 203.0.113.0/24 Null0
ipv6 route 2001:db8:6500::/48 Null0
!
route-map OWNED-PREFIX-ORIGIN permit 10
 set large-community 205013:100:0
!
router ospf
 ospf router-id 10.255.0.41
!
router ospf6
 ospf6 router-id 10.255.0.41
!
router bgp 205013
 bgp router-id 10.255.0.41
 no bgp default ipv4-unicast
 neighbor 10.255.0.21 remote-as internal
 neighbor 10.255.0.21 description TPE10-BB-RR-EXT-R1
 neighbor 10.255.0.21 update-source lo
 neighbor 10.255.0.22 remote-as internal
 neighbor 10.255.0.22 description TPE10-BB-RR-EXT-R2
 neighbor 10.255.0.22 update-source lo
 neighbor fd00:6500::21 remote-as internal
 neighbor fd00:6500::21 description TPE10-BB-RR-EXT-R1-V6
 neighbor fd00:6500::21 update-source lo
 neighbor fd00:6500::22 remote-as internal
 neighbor fd00:6500::22 description TPE10-BB-RR-EXT-R2-V6
 neighbor fd00:6500::22 update-source lo
 !
 address-family ipv4 unicast
  network 203.0.113.0/24 route-map OWNED-PREFIX-ORIGIN
  neighbor 10.255.0.21 activate
  neighbor 10.255.0.21 send-community all
  neighbor 10.255.0.22 activate
  neighbor 10.255.0.22 send-community all
 exit-address-family
 !
 address-family ipv6 unicast
  network 2001:db8:6500::/48 route-map OWNED-PREFIX-ORIGIN
  neighbor fd00:6500::21 activate
  neighbor fd00:6500::21 send-community all
  neighbor fd00:6500::22 activate
  neighbor fd00:6500::22 send-community all
 exit-address-family
!
