frr version 10.6.1
frr defaults traditional
hostname tpe10-svc-p-t1-r1
log stdout informational
service integrated-vtysh-config
!
interface lo
 ip address 10.255.100.2/32
 ip ospf area 0.0.0.0
 ip ospf passive
!
interface eth1
 description TPE10-SVC-PE-T1-R1
 ip address 10.100.0.1/31
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
!
interface eth2
 description TPE10-SVC-PE-T1-R2
 ip address 10.100.0.2/31
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
!
router ospf
 ospf router-id 10.255.100.2
!
mpls ldp
 router-id 10.255.100.2
 !
 address-family ipv4
  discovery transport-address 10.255.100.2
  !
  interface eth1
  !
  interface eth2
  !
 exit-address-family
!
