frr version 10.6.1
frr defaults traditional
hostname transit-a
log stdout informational
service integrated-vtysh-config
!
interface lo
 ip address 11.11.0.1/32
 ipv6 address 2001:db8:6510::1/128
!
interface eth1
 description ISP-TPE10-BB-TRA-T1-R1
 ip address 172.16.0.1/31
 ipv6 address 2001:db8:ff:1::1/127
!
ip route 0.0.0.0/0 Null0
ip route 11.11.0.0/16 Null0
ipv6 route ::/0 Null0
ipv6 route 2001:db8:6510::/48 Null0
!
ip prefix-list ISP-V4-IN seq 10 permit 203.0.113.0/24
ip prefix-list TRANSIT-A-V4-OUT seq 10 permit 0.0.0.0/0
ip prefix-list TRANSIT-A-V4-OUT seq 20 permit 11.11.0.0/16
ipv6 prefix-list ISP-V6-IN seq 10 permit 2001:db8:6500::/48
ipv6 prefix-list TRANSIT-A-V6-OUT seq 10 permit ::/0
ipv6 prefix-list TRANSIT-A-V6-OUT seq 20 permit 2001:db8:6510::/48
!
router bgp 1111
 bgp router-id 11.11.0.1
 no bgp default ipv4-unicast
 neighbor 172.16.0.0 remote-as 205013
 neighbor 172.16.0.0 description ISP-TPE10-BB-TRA-T1-R1
 neighbor 172.16.0.0 bfd
 neighbor 2001:db8:ff:1:: remote-as 205013
 neighbor 2001:db8:ff:1:: description ISP-TPE10-BB-TRA-T1-R1-V6
 neighbor 2001:db8:ff:1:: bfd
 !
 address-family ipv4 unicast
  network 0.0.0.0/0
  network 11.11.0.0/16
  neighbor 172.16.0.0 activate
  neighbor 172.16.0.0 prefix-list ISP-V4-IN in
  neighbor 172.16.0.0 prefix-list TRANSIT-A-V4-OUT out
  neighbor 172.16.0.0 maximum-prefix 5
 exit-address-family
 !
 address-family ipv6 unicast
  network ::/0
  network 2001:db8:6510::/48
  neighbor 2001:db8:ff:1:: activate
  neighbor 2001:db8:ff:1:: prefix-list ISP-V6-IN in
  neighbor 2001:db8:ff:1:: prefix-list TRANSIT-A-V6-OUT out
  neighbor 2001:db8:ff:1:: maximum-prefix 5
 exit-address-family
!
