frr version 10.6.1
frr defaults traditional
hostname ce-green-b
log stdout informational
service integrated-vtysh-config
!
interface eth1
 description TPE10-SVC-PE-T1-R2
 ip address 192.0.2.6/30
!
ip route 192.0.2.0/30 192.0.2.5
!
