frr version 10.6.1
frr defaults traditional
hostname service
log stdout informational
service integrated-vtysh-config
!
interface lo
 description INTERNAL-SERVICE-PREFIX
 ip address 10.255.0.100/32
 ip address 203.0.113.10/32
 ipv6 address fd00:6500::100/128
 ipv6 address 2001:db8:6500:100::10/128
 ip ospf area 0.0.0.0
 ip ospf passive
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 passive
!
interface eth1
 description CORE1
 ip address 10.0.0.11/31
 ipv6 address fd00:6500:0:6::1/127
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 network point-to-point
!
interface eth2
 description CORE2
 ip address 10.0.0.13/31
 ipv6 address fd00:6500:0:7::1/127
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 network point-to-point
!
router ospf
 ospf router-id 10.255.0.100
!
router ospf6
 ospf6 router-id 10.255.0.100
!
