frr version 10.6.1
frr defaults traditional
hostname tpe10-bb-core-t1-r2
log stdout informational
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.12/32
 ipv6 address fd00:6500::12/128
 ip ospf area 0.0.0.0
 ip ospf passive
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 passive
!
interface eth1
 description TPE10-BB-TRA-T1-R1
 ip address 10.0.0.3/31
 ipv6 address fd00:6500:0:2::1/127
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 network point-to-point
!
interface eth2
 description TPE10-BB-TRA-T1-R2
 ip address 10.0.0.7/31
 ipv6 address fd00:6500:0:4::1/127
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 network point-to-point
!
interface eth3
 description TPE10-BB-CORE-T1-R1
 ip address 10.0.0.9/31
 ipv6 address fd00:6500:0:5::1/127
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 network point-to-point
!
interface eth4
 description SERVICE
 ip address 10.0.0.12/31
 ipv6 address fd00:6500:0:7::/127
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 network point-to-point
!
interface eth5
 description TPE10-BB-RR-EXT-R1
 ip address 10.0.0.17/31
 ipv6 address fd00:6500:0:9::1/127
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 network point-to-point
!
interface eth6
 description TPE10-BB-RR-EXT-R2
 ip address 10.0.0.21/31
 ipv6 address fd00:6500:0:b::1/127
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 network point-to-point
!
interface eth7
 description TPE10-BB-ORG-T1-R1
 ip address 10.0.0.25/31
 ipv6 address fd00:6500:0:d::1/127
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 network point-to-point
!
interface eth8
 description TPE10-BB-ORG-T1-R2
 ip address 10.0.0.29/31
 ipv6 address fd00:6500:0:f::1/127
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 network point-to-point
!
router ospf
 ospf router-id 10.255.0.12
!
router ospf6
 ospf6 router-id 10.255.0.12
!
router bgp 205013
 bgp router-id 10.255.0.12
 no bgp default ipv4-unicast
 neighbor 10.255.0.21 remote-as internal
 neighbor 10.255.0.21 description TPE10-BB-RR-EXT-R1
 neighbor 10.255.0.21 update-source lo
 neighbor 10.255.0.22 remote-as internal
 neighbor 10.255.0.22 description TPE10-BB-RR-EXT-R2
 neighbor 10.255.0.22 update-source lo
 neighbor fd00:6500::21 remote-as internal
 neighbor fd00:6500::21 description TPE10-BB-RR-EXT-R1-V6
 neighbor fd00:6500::21 update-source lo
 neighbor fd00:6500::22 remote-as internal
 neighbor fd00:6500::22 description TPE10-BB-RR-EXT-R2-V6
 neighbor fd00:6500::22 update-source lo
 neighbor 172.31.255.11 remote-as internal
 neighbor 172.31.255.11 description TPE10-BB-RR-CTRL-R1-GOBGP
 neighbor 172.31.255.12 remote-as internal
 neighbor 172.31.255.12 description TPE10-BB-RR-CTRL-R2-GOBGP
 !
 address-family ipv4 unicast
  neighbor 10.255.0.21 activate
  neighbor 10.255.0.22 activate
  neighbor 172.31.255.11 activate
  neighbor 172.31.255.12 activate
 exit-address-family
 !
 address-family ipv6 unicast
  neighbor fd00:6500::21 activate
  neighbor fd00:6500::22 activate
  neighbor 172.31.255.11 activate
  neighbor 172.31.255.12 activate
 exit-address-family
!
