frr version 10.6.1
frr defaults traditional
hostname core1
log stdout informational
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.11/32
 ipv6 address fd00:6500::11/128
 ip ospf area 0.0.0.0
 ip ospf passive
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 passive
!
interface eth1
 description EDGE1
 ip address 10.0.0.1/31
 ipv6 address fd00:6500:0:1::1/127
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 network point-to-point
!
interface eth2
 description EDGE2
 ip address 10.0.0.5/31
 ipv6 address fd00:6500:0:3::1/127
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 network point-to-point
!
interface eth3
 description CORE2
 ip address 10.0.0.8/31
 ipv6 address fd00:6500:0:5::/127
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 network point-to-point
!
interface eth4
 description SERVICE
 ip address 10.0.0.10/31
 ipv6 address fd00:6500:0:6::/127
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 network point-to-point
!
interface eth5
 description RR1
 ip address 10.0.0.15/31
 ipv6 address fd00:6500:0:8::1/127
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 network point-to-point
!
interface eth6
 description RR2
 ip address 10.0.0.19/31
 ipv6 address fd00:6500:0:a::1/127
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 network point-to-point
!
router ospf
 ospf router-id 10.255.0.11
!
router ospf6
 ospf6 router-id 10.255.0.11
!
router bgp 205013
 bgp router-id 10.255.0.11
 no bgp default ipv4-unicast
 neighbor 10.255.0.21 remote-as internal
 neighbor 10.255.0.21 description RR1
 neighbor 10.255.0.21 update-source lo
 neighbor 10.255.0.22 remote-as internal
 neighbor 10.255.0.22 description RR2
 neighbor 10.255.0.22 update-source lo
 neighbor fd00:6500::21 remote-as internal
 neighbor fd00:6500::21 description RR1-V6
 neighbor fd00:6500::21 update-source lo
 neighbor fd00:6500::22 remote-as internal
 neighbor fd00:6500::22 description RR2-V6
 neighbor fd00:6500::22 update-source lo
 !
 address-family ipv4 unicast
  neighbor 10.255.0.21 activate
  neighbor 10.255.0.22 activate
 exit-address-family
 !
 address-family ipv6 unicast
  neighbor fd00:6500::21 activate
  neighbor fd00:6500::22 activate
 exit-address-family
!
