frr version 10.6.1
frr defaults traditional
hostname rr1
log stdout informational
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.21/32
 ipv6 address fd00:6500::21/128
 ip ospf area 0.0.0.0
 ip ospf passive
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 passive
!
interface eth1
 description CORE1
 ip address 10.0.0.14/31
 ipv6 address fd00:6500:0:8::/127
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 network point-to-point
!
interface eth2
 description CORE2
 ip address 10.0.0.16/31
 ipv6 address fd00:6500:0:9::/127
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 network point-to-point
!
router ospf
 ospf router-id 10.255.0.21
!
router ospf6
 ospf6 router-id 10.255.0.21
!
router bgp 205013
 bgp router-id 10.255.0.21
 bgp cluster-id 10.255.255.1
 no bgp default ipv4-unicast
 neighbor RR-CLIENTS peer-group
 neighbor RR-CLIENTS remote-as internal
 neighbor RR-CLIENTS update-source lo
 neighbor 10.255.0.1 peer-group RR-CLIENTS
 neighbor 10.255.0.2 peer-group RR-CLIENTS
 neighbor 10.255.0.11 peer-group RR-CLIENTS
 neighbor 10.255.0.12 peer-group RR-CLIENTS
 neighbor RR-CLIENTS-V6 peer-group
 neighbor RR-CLIENTS-V6 remote-as internal
 neighbor RR-CLIENTS-V6 update-source lo
 neighbor fd00:6500::1 peer-group RR-CLIENTS-V6
 neighbor fd00:6500::2 peer-group RR-CLIENTS-V6
 neighbor fd00:6500::11 peer-group RR-CLIENTS-V6
 neighbor fd00:6500::12 peer-group RR-CLIENTS-V6
 !
 address-family ipv4 unicast
  neighbor RR-CLIENTS activate
  neighbor RR-CLIENTS route-reflector-client
 exit-address-family
 !
 address-family ipv6 unicast
  neighbor RR-CLIENTS-V6 activate
  neighbor RR-CLIENTS-V6 route-reflector-client
 exit-address-family
!
