frr version 10.6.1
frr defaults traditional
hostname tpe10-bb-rr-ext-r2
log stdout informational
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.22/32
 ipv6 address fd00:6500::22/128
 ip ospf area 0.0.0.0
 ip ospf passive
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 passive
!
interface eth1
 description TPE10-BB-CORE-T1-R1
 ip address 10.0.0.18/31
 ipv6 address fd00:6500:0:a::/127
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 network point-to-point
!
interface eth2
 description TPE10-BB-CORE-T1-R2
 ip address 10.0.0.20/31
 ipv6 address fd00:6500:0:b::/127
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 network point-to-point
!
router ospf
 ospf router-id 10.255.0.22
!
router ospf6
 ospf6 router-id 10.255.0.22
!
router bgp 205013
 bgp router-id 10.255.0.22
 bgp cluster-id 10.255.255.1
 no bgp default ipv4-unicast
 neighbor RR-CLIENTS peer-group
 neighbor RR-CLIENTS remote-as internal
 neighbor RR-CLIENTS update-source lo
 neighbor 10.255.0.1 peer-group RR-CLIENTS
 neighbor 10.255.0.2 peer-group RR-CLIENTS
 neighbor 10.255.0.11 peer-group RR-CLIENTS
 neighbor 10.255.0.12 peer-group RR-CLIENTS
 neighbor 10.255.0.41 peer-group RR-CLIENTS
 neighbor 10.255.0.42 peer-group RR-CLIENTS
 neighbor RR-CLIENTS-V6 peer-group
 neighbor RR-CLIENTS-V6 remote-as internal
 neighbor RR-CLIENTS-V6 update-source lo
 neighbor fd00:6500::1 peer-group RR-CLIENTS-V6
 neighbor fd00:6500::2 peer-group RR-CLIENTS-V6
 neighbor fd00:6500::11 peer-group RR-CLIENTS-V6
 neighbor fd00:6500::12 peer-group RR-CLIENTS-V6
 neighbor fd00:6500::41 peer-group RR-CLIENTS-V6
 neighbor fd00:6500::42 peer-group RR-CLIENTS-V6
 neighbor 172.31.255.11 remote-as internal
 neighbor 172.31.255.11 description TPE10-BB-RR-CTRL-R1-GOBGP
 neighbor 172.31.255.12 remote-as internal
 neighbor 172.31.255.12 description TPE10-BB-RR-CTRL-R2-GOBGP
 !
 address-family ipv4 unicast
  neighbor RR-CLIENTS activate
  neighbor RR-CLIENTS route-reflector-client
  neighbor RR-CLIENTS send-community all
  neighbor 172.31.255.11 activate
  neighbor 172.31.255.11 addpath-tx-all-paths
  neighbor 172.31.255.12 activate
  neighbor 172.31.255.12 addpath-tx-all-paths
 exit-address-family
 !
 address-family ipv6 unicast
  neighbor RR-CLIENTS-V6 activate
  neighbor RR-CLIENTS-V6 route-reflector-client
  neighbor RR-CLIENTS-V6 send-community all
  neighbor 172.31.255.11 activate
  neighbor 172.31.255.11 addpath-tx-all-paths
  neighbor 172.31.255.12 activate
  neighbor 172.31.255.12 addpath-tx-all-paths
 exit-address-family
!
